###############################################################################
# File Name  : Makefile.config                                                #
# Description: This makefile contains the target specific project settings.   #
# Application: GNU Make version 3.79.1, by Richard Stallman and Roland McGrath#
#              Built for Windows32                                            #
# FAQ        : set the following values:                                      #
#              cpu clock                                                      #
#              derivative                                                     #
#              cpu instruction set                                            #
#                                                                             #
#-----------------------------------------------------------------------------#
#               C O P Y R I G H T                                             #
#-----------------------------------------------------------------------------#
# Copyright (c) 2006 by Vector Informatik GmbH.  All rights reserved.         #
#                                                                             #
#-----------------------------------------------------------------------------#
#               A U T H O R   I D E N T I T Y                                 #
#-----------------------------------------------------------------------------#
# Initials     Name                      Company                              #
# --------     ---------------------     -------------------------------------#
# UF           Ulrich Frank              Vector Informatik GmbH               #
# Fr           Markus Feninger           Vector Informatik GmbH               #
#-----------------------------------------------------------------------------#
#               R E V I S I O N   H I S T O R Y                               #
#-----------------------------------------------------------------------------#
# Date         Ver  Sign Description                                          #
# ----------   ---  ---- -----------------------------------------------------#
# 2002/11/22   1.0  Uf   Initial version                                      #
# 2006/03/23   1.1  Fr   Derivative PVF241PN added                            #
# 2006/11/04   1.2  Ard  Derivative PSF761 added                              #
# 2007/07/24   1.3  Ard  support SCC/HECC workaround                          #
#                        support CPU Optimization for CORTEXR4                #
# 2013/05/17   1.4  Ard  Added RTS_LIB                                        #
# 2013/11/22   1.5  kkn  Multiple TMS570/470 derivatives are now supported.   #
#                        Crystal and PLL frequency are now variable.          #
#                        BRS_TIMEBASE_Clock renamed to BRS_TIMEBASE.          #
# 2013/12/03   1.6  Fsn  REMOVED HECC/SCC WORKRAROUND defines (Nowhere used)  #
#                        Added OS_USECASE                                     #
#                        Added COMPILER_BASE                                  #
###############################################################################


#-----------------------------------------------------------------------------
#------------------------- MUST be filled out --------------------------------
# Internal cpu clock
# possible values are: Number e.g. 15
#-----------------------------------------------------------------------------
#
# Hint: The BRS_TIMEBASE_CLOCK (Frequency of the RTI module) depends on the clock
#       and PLL settings.
#       Check the startup code for those settings.
#       Default implementations of the startup code are available which
#       require the following settings for the timer
#
#  VEBN00140   (PSF761)   Quartz: 15Mhz     BRS_TIMEBASE_CLOCK:     15 Mhz
#  VEBN00106   (PVF241)   Quartz: 15Mhz     BRS_TIMEBASE_CLOCK:     15 Mhz
#  VEBN00191   (PVF249)   Quartz: 15Mhz     BRS_TIMEBASE_CLOCK:     15 Mhz
#  R1B31                  Quartz: 15Mhz     BRS_TIMEBASE_CLOCK:     30 MHz
#  VEBN00573   (MSF542)   Quartz:  8Mhz     BRS_TIMEBASE_CLOCK:     80 MHz
#  CORTEX_R4F             Quartz: 16Mhz     BRS_TIMEBASE_CLOCK:     80 MHz
#
#-----------------------------------------------------------------------------
# WARNING CHANGES - DO NOT COPY THAT VALUE FROM OLD VERSIONS OF MAKEFILE CONFIG

BRS_TIMEBASE_CLOCK = 80

EVA_BOARD     = VEBN00573

#-----------------------------------------------------------------------------
#------------------------- MUST be filled out --------------------------------
# Define used derivative
# possible values are:
#                       PVF241PN
#                       PVF249
#                       PVF348
#                       PSF761
#                       PSF764
#                       MF04207
#                       MF06607
#                       MSF542
#                       PSF761
#                       PSFC61
#                       PSFC66
#                       PSF762
#                       LS0432
#                       LS0805
#                       LS10206
#                       LS10216
#                       LS1227
#                       LS20216
#                       LS2124
#                       LS2125
#                       LS2134
#                       LS2135
#                       LS30336
#                       LS3134
#                       LS3135
#                       LS3137
#
# untested:             TMS470PSF... , TMS470M...
#-----------------------------------------------------------------------------
DERIVATIVE    = LS30336


#-----------------------------------------------------------------------------
#------------------------- MUST be filled out --------------------------------
# Define cpu instruction set
#
# possible values are: THUMB ARM
#-----------------------------------------------------------------------------
INSTRUCTION_SET = THUMB

#-----------------------------------------------------------------------------
#------------------------- MUST be filled out --------------------------------
# Select the type of used OS 
# possible values are:      BRS      OS Emulation used
#                           OSEKOS   Osek OS used
#                           ASR      Non-SafeCtx ASR OS used
#
#-----------------------------------------------------------------------------
OS_USECASE =

#-----------------------------------------------------------------------------
#------------------------- MUST be filled out --------------------------------
# Activate CPU optimization
#
# Use DEFAULT for all TMS470 derivatives (will work on all derivatives, compiler
#                                         will create code for use with all ARM7 CPUs)
#
# Use CORTEX_R4 for all TMS570 derivatives, if supported and required
#
# Possible values are: DEFAULT CORTEX_R4 CORTEX_M3
#
#-----------------------------------------------------------------------------
CPU_OPTIMIZATION = CORTEX_R4

#------------------------------------------------------------------------------
#------------------------- Can be filled out ---------------------------------
# Define Compiler path
# E.g.: COMPILER_BASE = D:\uti\TMS570\TI_4_4_10_114
#------------------------------------------------------------------------------
COMPILER_BASE = D:\uti\TI\4.9.5
#------------------------- Can be filled out --------------------------------
# Filename of the runtime support library
# If left empty, the library file will be chosen based on the used compiler options
# Example: rtsv7R4_T_be_eabi.lib
#-----------------------------------------------------------------------------
RTS_LIB =

#-----------------------------------------------------------------------------
#------------------------- Can be filled out --------------------------------
# Define usage of can_32.c
#
# Use for HeccScc HLL IDX CAN Driver
# Do not use for DCAN Driver
#
# possible values are: 1 0
#
#-----------------------------------------------------------------------------
USECAN32 = 0
CONFIG_RAMUSED   = 0
